---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/articles":
    get:
      summary: list articles
      tags:
      - Get articles
      description: Find list of articles
      security:
      - Bearer: {}
      parameters:
      - name: Authorization
        in: header
        required: true
        description: Client token
        schema:
          type: string
      - name: query
        in: path
        required: true
      responses:
        '200':
          description: successful
  "/api/v1/login":
    post:
      summary: create session
      tags:
      - Login
      description: Creates a new jwt
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
              - email
              - password
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
