---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/articles":
    get:
      summary: index articles
      tags:
      - Articles
      parameters:
      - name: Authorization
        in: header
        required: true
        description: Client token
        default: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpZCI6IjEiLCJlbWFpbCI6InRlc3RAdGVzdC50ZXN0IiwiZXhwIjo3OTQxODAxNjAwfQ.zpLErslgllgn3NxqrDjz5jxcZG0uOYiuqQhn-Ey3ToI
        schema:
          type: string
      responses:
        '200':
          description: ok
        '401':
          description: unauthorized
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                query:
                  type: string
                page:
                  type: integer
              required:
              - query
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
