default: &default
  adapter: postgresql
  encoding: unicode
  database: talker
  port: 54320
  host: 127.0.0.1
  username: myuser
  password: qwerty
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: talker_development

test:
  <<: *default
  database: talker_test

production:
  <<: *default
  database: talker
