default: &default
  adapter: postgresql
  encoding: unicode
  database: talker
  port: <%= ENV.fetch("DATABASE_PORT") %>
  host: <%= ENV.fetch("DATABASE_HOST") %>
  username: <%= ENV.fetch("DATABASE_USER") %>
  password:  <%= ENV.fetch("DATABASE_PASSWORD") %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: talker_development

test:
  <<: *default
  database: talker_test

production:
  <<: *default
  database: talker
